steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'shivam@instance-23'
  - '--zone'
  - 'us-central1-a'
  - '--command'
  - |
    cd /home/shivam/workspace
    git clone https://github.com/shivam2804-brahm/todorepoi12.git
    cd /home/shivam/workspace/todorepoi12
    go mod init github.com/shivam/todorepoi12
    go mod tidy
    go build main.go
    ./main

options:
  logging: 'CLOUD_LOGGING_ONLY'
